#!/usr/bin/env python3

"""Downloads a file with wget, and allows file renaming in one go"""

import argparse
import subprocess
import sys
import os
from pathlib import Path

parser = argparse.ArgumentParser()

parser.add_argument('url', type=str, help='The url of the file to download')
parser.add_argument('-r', '--rename', help='The new name of the newly downloaded file')
args = parser.parse_args()

url = args.url
rename = args.rename if args.rename else None

def main():
    if rename:
        rename_downloaded_file(rename)
    else:
        subprocess.run(f'wget "{url}"', shell=True)


def rename_downloaded_file(new_name):
    # store file status before the download
    cwd = os.getcwd()
    files_before = set(x.name for x in Path.iterdir(Path(cwd)))

    # download the file and detect the new file
    subprocess.run(f'wget "{url}"', shell=True)
    files_after = set(x.name for x in Path.iterdir(Path(cwd)))
    new_file = "".join(files_after.difference(files_before))

    if not new_file:
        sys.exit("No file was downloaded. Check the url and try again")

    # rename the new file
    subprocess.run(f'mv "{new_file}" "{new_name}"', shell=True)

if __name__ == '__main__':
    main()
