#!/usr/bin/env python3

import sys
import subprocess
from textwrap import dedent

script_name = ',mainh'
argvlen = len(sys.argv)

if argvlen < 2 or argvlen > 3:
    sys.exit(f"usages: \n{script_name} new \n{script_name} <prototype> <description>")

# write the guards into the file
if argvlen == 2:
    subprocess.run("touch main.h", shell=True)
    content = dedent("""
#ifndef MY_HEADER_H
#define MY_HEADER_H
#endif /* MAIN_H */
    """.strip()
    )

    with open('main.h', 'w', encoding='utf-8') as f:
        f.write(content)
    print('New main.h written')
    sys.exit()

prototype = sys.argv[1]
desc = sys.argv[2]

# check that the arguments have not been switched
if desc.endswith(');'):
    print('You may have swapped the prototype and description')
    print("Here's a reminder of the order:")
    print(f'{script_name} <prototype> <description>')
    sys.exit()

lines = []

with open('main.h', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# add description, prototype, with additional new lines if necessary
last_line = lines.pop()
if lines[-1].startswith('#define MY_HEADER_H'):
    lines.append('\n')
lines.append(f'/* {desc} */\n')
lines.append(f'{prototype}\n\n')
lines.append(last_line)

# write new content to 'main.h'
with open('main.h', 'w', encoding='utf-8') as f:
    f.writelines(lines)
