#!/usr/bin/env python

""" Replicates the customized way that `make` works in a CS50 C class. 
i.e. without the need to specify the `.c` at the end of the file, or to link
the libraries required.

The script assumes that you already have `clang` installed in your computer,
as this is what is used to compile the C code.
"""
import subprocess
import os
import sys

if not len(sys.argv) >= 2:
    sys.exit('usage: ,make file')

if sys.argv[1].endswith('.c'):
    sys.exit("You shouldn't include the `.c` at the end of the file name.")

program = sys.argv[1]
file = f'{program}.c'

# edit this line to add more libraries for your purposes
libs = {
    '50': 'cs50',
    'm': 'm',
}

link_sequence = ''

for lib in libs:
    link_sequence += f' -l{libs[lib]}'

# compile the file with clang
subprocess.run(f'clang {file} -o {program.strip()} {link_sequence}', shell=True)
