#!/usr/bin/env python3
"""Switches between any number of zsh themes by changing the `ZSH_THEME` option in the 
.zshrc file"""

from pathlib import Path
import os
import subprocess
import re
import sys

# edit this list to swap between themes of your own
themes_to_swap = ['aussiegeek', 'bira', 'kardan']

# edit this line if your .zshrc file is in a different location
zshrc_path = Path(os.getenv('HOME'), '.zshrc')
zsh_themes_path = Path(os.getenv('HOME'), '.oh-my-zsh', 'themes')

# verify that the provided themes exist in the themes location
# default location checked is ~/.oh-my-zsh/themes
for theme in themes_to_swap:
    grep_command = f'ls -a {str(zsh_themes_path)} | grep {theme}'
    legal_themes = subprocess.run(grep_command, capture_output=True, text=True, shell=True)
    output = legal_themes.stdout
    if not output:
        sys.exit(f'{theme} is not a recognized theme.\nPlease check the spelling and try again.')

# make a backup of the original .zshrc file
if not Path.exists(Path(str(zshrc_path) + '.pre_zshthemeswap')):
    subprocess.run(['cp', zshrc_path, str(zshrc_path) + '.pre_zshthemeswap'])

with open(zshrc_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

for i, line in enumerate(lines):
    if not line.startswith('ZSH_THEME='):
        continue
    match = re.search(r'="(?P<theme>\w*)"', line)
    current_theme = match.group('theme')

    if current_theme not in themes_to_swap:
        # make the first theme in the list the new theme
        new_theme = themes_to_swap[0]
    else:
        # wrap around to the beginning, if the current theme is the last one
        if themes_to_swap[-1] == current_theme:
            new_theme = themes_to_swap[0]
        else:
            new_theme_index = themes_to_swap.index(current_theme) + 1
            new_theme = themes_to_swap[new_theme_index]

    # replace the current theme with the new theme
    lines[i] = f'ZSH_THEME="{new_theme}"\n'

# replace the contents of the .zshrc file
with open(zshrc_path, 'w', encoding='utf-8') as f:
    f.writelines(lines)

# source the new .zshrc file and open a new zsh session with the new theme applied
subprocess.run(f'zsh -c "source {str(zshrc_path)}"', shell=True)
subprocess.run('zsh')
