#!/usr/bin/env python3
"""Switches between 2 zsh themes by changing the `ZSH_THEME` option in the 
.zshrc file"""

from pathlib import Path
import os
import subprocess
import re

# edit this list to swap between two themes of your own
themes_to_swap = ['bira', 'demo']

# edit this line if your .zshrc file is in a different location
zshrc_path = Path(os.getenv('HOME'), '.zshrc')

# make a backup of the original .zshrc file
subprocess.run(['cp', zshrc_path, str(zshrc_path) + '.pre-themeswap'])

with open(zshrc_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()
    for i, line in enumerate(lines):
        if line.startswith('ZSH_THEME='):
            match = re.search(r'="(?P<theme>\w*)"', line)
            old_theme = match.group('theme')
            themes_to_swap.remove(old_theme)
            new_theme = ''.join(themes_to_swap)

            # replace the old theme with the new theme
            lines[i] = f'ZSH_THEME="{new_theme}"\n'

# replace the contents of the .zshrc file
with open(zshrc_path, 'w', encoding='utf-8') as f:
    f.writelines(lines)

# source the new .zshrc file and open a new zsh session with the new theme applied
subprocess.run(f'zsh -c "source {str(zshrc_path)}"', shell=True)
subprocess.run('zsh')
