#!/usr/bin/env python3

from pathlib import Path
import argparse

def is_venv_dir(dir: str) -> bool:
	"""Return True if the directory is a virtual env dir
	i.e. starts with 'venv' or 'env' or 'venv-'
	"""
	return dir.startswith('venv') or dir.startswith('env') or dir.startswith('venv-')

def main():
	parser = argparse.ArgumentParser(description='Find and activate a virtual environment in the current directory, or a starting directory.')
	parser.add_argument('-d', type=str, default='.', help='Starting directory to search for virtual environments (default: current directory)')

	args = parser.parse_args()

	# get all dirs in the current directory
	curr_dir = Path(args.d).resolve()
	if not curr_dir.is_dir():
		print(f'Error: {curr_dir} is not a directory.')
		exit(1)

	dirs = [
        dir
        for dir in curr_dir.iterdir()
        if dir.is_dir() and is_venv_dir(dir.name)
	]

	if not dirs:
		print('No virtual environment found in the current directory.')
		exit(1)

	venv_dir = dirs[0]

	activation = venv_dir / 'bin' / 'activate'
	print(f'source {activation}')

if __name__ == '__main__':
	main()
